---
title: "ggplot2 via Formulas"
author: "Daniel Kaplan"
date: "March 17, 2015"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{ggplot2 via Formulas}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r include=FALSE}
library(ggplot2)
library(mosaicData)
library(dplyr)
library(formula.tools)
```

```{r}
foo <- ggplot(data=CPS85, aes(x=age, y=wage)) 
```

The first argument is either a formula or a `gg` class object. The second argument is either missing or a formula.


```{r}
scatter <- function(.first, .second, data=NULL, ...) {
  if ( !any(inherits(.first, c("formula","gg"))) )
    stop("First argument must be formula or an existing plot.")
  if (inherits(.first, "formula")) {
    xvar <- rhs(.first) # There may be more
    yvar <- lhs(.first) 
    if (is.null(data)) {
      # Construct a data frame from the outside environment
      # not yet implemented
    }
    mapping <- aes_q(x=xvar, y=yvar)
    Plot <- ggplot(data=data, mapping) + geom_point(...)
    
  } else {
    # input is a previous gg object
    if (!missing(.second)) { # there's a new formula
      xvar <- rhs(.second)
      yvar <- lhs(.second)
      mapping <- aes_q(x = xvar, y = yvar)
      if (is.null(data)) { 
        # use data from the previous object
        D <- .first$data
      } else {
        D <- data
      }
      Plot <- .first + geom_point(data=D, mapping, ...)
    }
  }
  return(Plot)
}

```

Tests
```{r}
scatter(wage ~ age, data=CPS85)
```

```{r}
scatter(wage ~ age, data=CPS85) %>%
  scatter(educ ~ age, color="red")
```
